### ISSUE TITLE
aar发布的问题

### ISSUE THREAD

**Issue by cxss** [openproject/LessCode#6]
您好，我参照您的“使用Gradle发布aar项目到JCenter仓库”文章，进行aar发布时，gradle配置文件配好，进行编译时报错。于是我clone了您的项目，在studio中能编译通过，但是执行gradlew编译时也报错，错误包括 package android.support.v4.graphics.drawable does not exist / can't find symble  com.jayfeng.lesscode.core.R; 等等，看起来是依赖库找不到，.R也找不到（我的工程也是这类错）。请问您知道问题出在哪里吗？谢谢

**Comment by openproject** [comment]
用的是android studio的哪个版本？

**Comment by cxss** [comment]
您好，我用的是android studio 1.5.1，com.android.tools.build:gradle:1.3.0。看起来是javadoc生成时引用不到android.support的库导致的。目前初步找到了一些解决办法，还在进一步尝试中。谢谢！

**Comment by openproject** [comment]
我这边现在用的是android studio 2.1.1/2.1.2，是OK的．
注释掉javadoc试试：
artifacts {
    // archives javadocJar
    archives sourcesJar
}

**Comment by cxss** [comment]
注掉javadocJar倒是不会报错的，就怕不传doc通不过审核。我再试试，谢谢了！

**Comment by openproject** [comment]
第一次是要javadoc的，通过了之后其实是不需要再审核的．
你现在的状态是第一次提交，还是已经审核通过了只是更新？
