### ISSUE TITLE
aar发布问题

### ISSUE THREAD

**Issue by ouyangzn** [openproject/LessCode#7]
参照你的文章配置完后，上传时报错：
HTTP/1.1 404 Not Found [message:Repo 'maven' was not found]
上传失败，这个问题要怎么解决？

**Comment by openproject** [comment]
这个我没碰到过，我只能建议你翻墙试试

**Comment by ouyangzn** [comment]
好吧，还是谢啦

**Comment by openproject** [comment]
这是账户的问题，有些账户在bintray上没有自动建立maven仓库，最近了解到这个信息

**Comment by ouyangzn** [comment]
嗯，这个已经知道了，谢谢，你居然还能看到这个问题( ⊙ o ⊙ )
